# Problem 1 

In [1]:
import numpy as np

# 2
array = np.array([3, 1, 5, 2, 4])
print("Oluşturulan array: ", array)

# 3
sirali_array = np.sort(array)
print("Sıralanmış array: ", sirali_array)



Oluşturulan array:  [3 1 5 2 4]
Sıralanmış array:  [1 2 3 4 5]


# Problem 2

In [30]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np

matris = np.array([10, 15, 30, 45, 60])
print(matris)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
import numpy as np

matris = np.arange(5, 16)
print(matris)

 # 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
import numpy as np

matris = np.arange(50, 101, 5)
print(matris)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
import numpy as np

matris = np.zeros(10)
print(matris)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
import numpy as np

matris = np.ones(10)
print(matris)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
import numpy as np

matris = np.linspace(0, 100, 5)
print(matris)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

import numpy as np

matris = np.random.randint(10, 31, size=5)
print(matris)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
import numpy as np

matris = np.random.uniform(-1, 1, size=10)
print(matris)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
import numpy as np

matris = np.random.uniform(-1, 1, size=10)
print(matris)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
#reshaped_matris = np.reshape(matris, (satir_sayisi, sutun_sayisi))
#print("Satır toplamları:", np.sum(reshaped_matris, axis=1))
#print("Sütun toplamları:", np.sum(reshaped_matris, axis=0))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print("En büyük değer:", np.max(matris))
print("En küçük değer:", np.min(matris))
print("Ortalama:", np.mean(matris))

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index = np.argmax(matris)
print("En büyük değerin indeksi:", max_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
dizi = np.arange(10, 21)
print(dizi[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(matris[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print("İlk satır:", matris[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print("2. satır, 3. sütun:", matris[1, 2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
reshaped_matris = np.reshape(matris, (satir_sayisi, sutun_sayisi))
print("Kareleri:", np.square(reshaped_matris))


# 18- Üretilen matrisin her bir elemanının karesini alınız.
reshaped_matris = np.reshape(matris, (satir_sayisi, sutun_sayisi))
print("Kareleri:", np.square(reshaped_matris))































[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[20 25 28 19 19]
[ 0.12782104 -0.20171089 -0.04508065 -0.83179098  0.70498499  0.57796393
  0.60098356  0.25063433  0.87992104 -0.96771789]
[-0.35715457 -0.77632321 -0.86724303 -0.31756711  0.55215928  0.78707548
  0.74265597 -0.25865401  0.01973441  0.19924214]
En büyük değer: 0.787075477628278
En küçük değer: -0.8672430308816623
Ortalama: -0.027607465676126285
En büyük değerin indeksi: 5
[10 11 12]
[ 0.19924214  0.01973441 -0.25865401  0.74265597  0.78707548  0.55215928
 -0.31756711 -0.86724303 -0.77632321 -0.35715457]
İlk satır: -0.3571545739904787


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed