# Problem 1

In [1]:
import numpy as np

# 1
matris = np.random.randint(0, 10, size=(5,))

# 2
print(matris.shape)  # (5,)

# 3
matris = matris.reshape(5, 1)

# 4
print(matris.ndim)  # 2



(5,)
2


# Problem 2

In [3]:
import numpy as np

# 1
matris = np.arange(1, 10, 2).reshape(5, 1)
print("Üretilen matris:\n", matris)

# 2
parcalar = np.split(matris, 5)
print("Parçalanan matrisler:")
for p in parcalar:
    print(p)

# 3
birlesik_matris = np.concatenate(parcalar, axis=1)
print("Birleştirilmiş matris:\n", birlesik_matris)


Üretilen matris:
 [[1]
 [3]
 [5]
 [7]
 [9]]
Parçalanan matrisler:
[[1]]
[[3]]
[[5]]
[[7]]
[[9]]
Birleştirilmiş matris:
 [[1 3 5 7 9]]


# Problem 3

In [4]:
import numpy as np

# 1
matris = np.random.randint(5, 100, size=(5,2)) * 2
print("Üretilen matris:\n", matris)

# 2
print("Matrisin boyutu: ", matris.shape)
print("Matrisin eleman sayısı: ", matris.size)
print("Matrisin veri tipi: ", matris.dtype)
print("Matrisin elemanlarının toplamı: ", matris.sum())
print("Matrisin en küçük elemanı: ", matris.min())
print("Matrisin en büyük elemanı: ", matris.max())
print("Matrisin ortalama değeri: ", matris.mean())



Üretilen matris:
 [[ 36  38]
 [ 74  78]
 [126 120]
 [ 40  72]
 [ 98  78]]
Matrisin boyutu:  (5, 2)
Matrisin eleman sayısı:  10
Matrisin veri tipi:  int32
Matrisin elemanlarının toplamı:  760
Matrisin en küçük elemanı:  36
Matrisin en büyük elemanı:  126
Matrisin ortalama değeri:  76.0
